# Generated by Django 4.0.2 on 2023-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emailsent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsent',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
