# Generated by Django 4.0.2 on 2023-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='newemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
